name: Deploy preview site
on:
  pull_request:
    branches: ["main"]
concurrency: preview-${{ github.ref }}

jobs:
  build:
    uses: ./.github/workflows/build.yml
  deploy-preview:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: download-builds
        uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: build

      - name: Deploy
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./build/
