name: Update dbml

on:
  push:
    branches: [main]
    paths:
      - packages/document/dbml/*
      - .github/workflows/update-dbml.yml

jobs:
  build-dbdocs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install dbdocs
        run: sudo npm install -g dbdocs

      - name: Build dbdocs
        env:
          DBDOCS_TOKEN: ${{ secrets.DBDOCS_TOKEN }}
        run: |
          dbdocs build packages/document/dbml/shuttlepub.dbml --project shuttlepub
          dbdocs build packages/document/dbml/emumet.dbml --project emumet
